// English UI strings — the source of truth for the dictionary shape.
// is.ts is typed against `Dict`, so a key missing there fails the build.
// Content (articles, schedule entries) is NOT here — only UI chrome.
// Deliberately no `as const`: literal types would force is.ts to carry
// byte-identical strings.

const en = {
  meta: {
    title: "Iceland Eclipse — Festival Companion",
    ogTitle: "Iceland Eclipse — Festival Guide",
    description:
      "Festival map, schedule, and guides. Iceland Eclipse, Snæfellsnes Peninsula, 11–15 August 2026.",
    baseUrl: "https://app.icelandeclipse.com",
  },
  nav: {
    home: "Home",
    map: "Map",
    schedule: "Schedule",
    guides: "Guides",
    profile: "Profile",
    dates: "11–15 Aug 2026",
  },
  home: {
    eyebrow: "Total Solar Eclipse · Snæfellsnes Peninsula",
    heroTitle: "Your Companion for the Gathering",
    heroBody:
      "Everything you need on the ground: the festival map, the full schedule, and guides to the gathering.",
    ticketPre: "Don't have your ticket yet?",
    ticketCta: "Secure your spot now",
    ticketHref: "https://feverup.com/m/416569",
    planTrip: "Plan your trip",
    shuttlesTitle: "Shuttles",
    shuttlesBlurb: "Book your ride to and from the site.",
    experiencesTitle: "Experiences",
    experiencesBlurb: "Add-on tours and experiences around the peninsula.",
    featured: "Featured Articles",
    seeAll: "See all",
    open: "Open",
    mapTitle: "Festival Map",
    mapBlurb: "Stages, food, water, medical — find your way around the site.",
    scheduleTitle: "Schedule",
    scheduleBlurb: "Every talk, ceremony and set across five days and nine stages.",
    guidesTitle: "Guides",
    guidesBlurb: "Field notes and essentials for the eclipse, the land, and the gathering.",
    faqTitle: "Attendee FAQ",
    faqBlurb: "Answers on travel, packing, campgrounds, meals and the programme.",
    faqHref: "https://icelandeclipse.com/faq",
    sponsorsTitle: "Partners",
    sponsorsBlurb: "The partners and producers making the gathering possible.",
  },
  schedule: {
    metaTitle: "Schedule — Iceland Eclipse",
    tabSchedule: "Schedule",
    tabLineup: "Lineup",
    timeline: "Timeline",
    list: "List",
    allStages: "All stages",
    late: "Late",
    now: "Now",
    live: "Live",
    tbc: "TBC",
    panel: "Panel",
    nothingScheduled: "Nothing scheduled for this day yet.",
    searchPlaceholder: "Search participants…",
    noMatch: "No participants match.",
    nParticipants: (n: number) => `${n} participant${n === 1 ? "" : "s"}`,
    nSpeakers: (n: number) => `${n} speakers`,
    speakersTapHint: (n: number) => `${n} speakers · tap for bio & sessions`,
    alsoAppearing: "Also appearing",
    noBio: "No bio yet.",
  },
  guides: {
    metaTitle: "Guides — Iceland Eclipse",
    eyebrow: "Know Before You Go",
    title: "Guides",
    intro:
      "Everything worth reading before and during the gathering: packing, camping, the eclipse itself, and what makes this peninsula special.",
    allGuides: "All guides",
    categoryLabels: {
      "quick-guides": "Quick Guides",
      "highlights-news": "Highlights & News",
    } as Record<string, string>,
  },
  map: {
    metaTitle: "Festival Map — Iceland Eclipse",
  },
  sponsors: {
    metaTitle: "Partners — Iceland Eclipse",
    metaDescription:
      "The partners and producers making the Iceland Eclipse gathering possible.",
    eyebrow: "Iceland Eclipse",
    title: "Partners & Producers",
    intro: "The partners and producers making the gathering possible.",
    // Group titles / partner categories come from sponsors.json (destined to be
    // regenerated by a future sync), so we map them here instead of forking the
    // file. A missing key falls back to the English value from the JSON.
    groupTitles: {} as Record<string, string>,
    categoryLabels: {} as Record<string, string>,
  },
  // Schedule content-type chips (fixed set from the ROS sheet). English shows
  // the raw value; is.ts maps them. Missing key → raw value.
  categories: {} as Record<string, string>,
  // Locale-specific stage descriptor overrides (only where the shared
  // STAGE_STYLES `sub` is an English descriptor, not an Icelandic name).
  stageSubs: {} as Record<string, string>,
  sw: {
    updated: "Schedule updated",
    refresh: "Refresh",
  },
  notFound: {
    title: "Page not found",
    body: "That page doesn't exist — it may have moved.",
    backHome: "Back home",
  },
  dateLocale: "en-GB",
};

export type Dict = typeof en;
export default en;
